//! Rendering a hyprlock config that carries one wallpaper per monitor.
//!
//! Replaces `hyprrandlock.fish`, which appended a `background` block per
//! monitor to a copy of the user's config and ran `hyprlock -c` on it. Three
//! things are done differently here, each for a reason:
//!
//! * **Monitors are keyed by description, not port.** `hyprctl monitors` on a
//!   two-identical-display setup reports `DP-9` and `DP-10` with descriptions
//!   differing only in serial, and DPMS cycles can reshuffle which port is
//!   which. `monitor = desc:<description>` follows the panel, not the plug.
//! * **The base config's monitor-less `background` is kept and out-ranked.**
//!   Widget matching in hyprlock is additive, so a monitor-less block plus a
//!   per-monitor block yields two backgrounds for that monitor. The scripts
//!   relied on the appended one happening to draw last. An explicit `zindex`
//!   makes it deterministic — and the fallback has to stay, because a monitor
//!   that appears *after* the lock is taken (a DPMS wake) can only be matched
//!   by a monitor-less block, and without one its surface renders transparent.
//! * **Values that hyprlang cannot round-trip are refused.** A path is read to
//!   end of line, so a newline in a filename would inject config, and `#`
//!   would truncate it.

use std::fmt::Write as _;
use std::path::PathBuf;

/// `zindex` for the per-monitor blocks this module generates.
///
/// hyprlock defaults a background to `-1` and draws in ascending `zindex`, so
/// anything above `-1` is painted after — and therefore over — the user's
/// monitor-less fallback. Being explicit is the point: at equal `zindex` the
/// draw order falls out of a sort whose stability is not guaranteed.
const GENERATED_ZINDEX: i32 = 0;

/// hyprlock's own default for a `background` that does not set `zindex`.
const HYPRLOCK_DEFAULT_ZINDEX: i32 = -1;

// The whole point of being explicit: enforce the ordering at compile time
// rather than asserting it in a test that could be deleted.
const _: () = assert!(GENERATED_ZINDEX > HYPRLOCK_DEFAULT_ZINDEX);

/// Blur applied to the generated backgrounds, mirroring hyprlock's own keys.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Blur {
    pub passes: u32,
    pub size: u32,
}

impl Default for Blur {
    fn default() -> Self {
        // The values the user's existing hyprlock.conf already uses.
        Self { passes: 1, size: 3 }
    }
}

/// One monitor as hyprlock should be told to match it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockMonitor {
    /// Port name, e.g. `DP-9`.
    pub name: String,
    /// Human description, e.g. `Dell Inc. DELL U2518D 3C4YP95TBQ5L`. Empty
    /// when the compositor did not report one.
    pub description: String,
    pub wallpaper: PathBuf,
}

impl LockMonitor {
    /// How to write this monitor in a hyprlock `monitor =` field.
    ///
    /// Prefers the description, which survives a port reshuffle. hyprlock
    /// prefix-matches `desc:`, so the trailing serial does not have to be
    /// reproduced exactly — but it is, since it is the only thing telling two
    /// identical displays apart.
    #[must_use]
    pub fn key(&self) -> String {
        if self.description.trim().is_empty() || !is_hyprlang_safe(&self.description) {
            self.name.clone()
        } else {
            format!("desc:{}", self.description.trim())
        }
    }
}

/// Whether a string can be used as a hyprlang value without changing meaning.
///
/// hyprlang reads a value to end of line and treats `#` as a comment, so a
/// newline would let a filename inject configuration and a `#` would silently
/// truncate the path.
#[must_use]
pub fn is_hyprlang_safe(value: &str) -> bool {
    !value.contains(['\n', '\r', '#'])
}

/// A path that cannot be expressed in the config, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rejected {
    pub monitor: String,
    pub path: PathBuf,
    pub reason: &'static str,
}

/// The generated config plus whatever had to be dropped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rendered {
    pub config: String,
    pub rejected: Vec<Rejected>,
}

/// Build a hyprlock config from `base` plus one background per monitor.
///
/// `base` is copied verbatim and never parsed — it is the user's own file and
/// may contain anything, including the `auth { fingerprint { … } }` block that
/// vendoring a template would silently drop.
#[must_use]
pub fn render_config(base: &str, monitors: &[LockMonitor], blur: Blur) -> Rendered {
    let mut rejected = Vec::new();
    let mut out = String::with_capacity(base.len().saturating_add(256));
    out.push_str(base);
    if !base.ends_with('\n') {
        out.push('\n');
    }

    out.push_str(
        "\n# --- generated by obayebar: one background per monitor ---\n\
         # Regenerated on every lock. Edits here are lost; change\n\
         # [lock] in obayebar's config.toml instead.\n",
    );

    let mut sorted: Vec<&LockMonitor> = monitors.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    for monitor in sorted {
        let Some(path) = monitor.wallpaper.to_str() else {
            rejected.push(Rejected {
                monitor: monitor.name.clone(),
                path: monitor.wallpaper.clone(),
                reason: "path is not valid UTF-8",
            });
            continue;
        };
        if !is_hyprlang_safe(path) {
            rejected.push(Rejected {
                monitor: monitor.name.clone(),
                path: monitor.wallpaper.clone(),
                reason: "path contains a newline or '#', which hyprlang cannot quote",
            });
            continue;
        }
        let _ = write!(
            out,
            "\nbackground {{\n    \
             monitor = {}\n    \
             path = {}\n    \
             blur_passes = {}\n    \
             blur_size = {}\n    \
             zindex = {}\n\
             }}\n",
            monitor.key(),
            path,
            blur.passes,
            blur.size,
            GENERATED_ZINDEX,
        );
    }

    Rendered {
        config: out,
        rejected,
    }
}

/// Whether `base` has a `background` block with no `monitor` set.
///
/// Such a block is what covers a monitor that appears while the session is
/// already locked, so its absence is worth warning about rather than fixing
/// silently — the base config belongs to the user.
///
/// Deliberately a shallow scan, not a hyprlang parser: it tracks brace depth
/// and looks at the `background` blocks' own keys. Nested blocks inside a
/// background would confuse it, which is why a false answer only downgrades a
/// hint and never changes the generated output.
#[must_use]
pub fn has_monitorless_background(base: &str) -> bool {
    let mut depth: usize = 0;
    let mut in_background_at: Option<usize> = None;
    let mut saw_monitor_value = false;

    for raw in base.lines() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }

        if line.ends_with('{') {
            let name = line.trim_end_matches('{').trim();
            depth = depth.saturating_add(1);
            if name == "background" && in_background_at.is_none() {
                in_background_at = Some(depth);
                saw_monitor_value = false;
            }
            continue;
        }

        if line == "}" {
            if in_background_at == Some(depth) {
                if !saw_monitor_value {
                    return true;
                }
                in_background_at = None;
            }
            depth = depth.saturating_sub(1);
            continue;
        }

        if in_background_at == Some(depth) {
            if let Some(value) = line.strip_prefix("monitor") {
                let value = value.trim_start().strip_prefix('=').unwrap_or("").trim();
                if !value.is_empty() {
                    saw_monitor_value = true;
                }
            }
        }
    }

    false
}

/// Where the generated config is written.
///
/// The runtime dir, not `/tmp`: it is mode 700, so a config naming the user's
/// wallpaper paths is not world-readable, and it is cleared on logout.
#[must_use]
pub fn generated_path() -> Option<PathBuf> {
    crate::xdg::runtime_dir().map(|d| d.join("hyprlock.conf"))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;

    fn monitor(name: &str, description: &str, wallpaper: &str) -> LockMonitor {
        LockMonitor {
            name: name.to_string(),
            description: description.to_string(),
            wallpaper: PathBuf::from(wallpaper),
        }
    }

    #[test]
    fn base_is_copied_verbatim() {
        // The user's own keys — notably an auth/fingerprint block — must
        // survive untouched.
        let base = "general {\n    hide_cursor = true\n}\nauth {\n    fingerprint {\n        enabled = true\n    }\n}\n";
        let out = render_config(base, &[], Blur::default());
        assert!(out.config.starts_with(base));
        assert!(out.config.contains("fingerprint"));
    }

    #[test]
    fn missing_trailing_newline_does_not_glue_lines() {
        let out = render_config("general {\n}\n# no trailing newline", &[], Blur::default());
        assert!(
            !out.config.contains("newline#"),
            "generated section must start on its own line"
        );
        assert!(out.config.contains("no trailing newline\n"));
    }

    #[test]
    fn one_block_per_monitor_keyed_by_description() {
        let out = render_config(
            "general {\n}\n",
            &[
                monitor("DP-9", "Dell Inc. U2518D TBQ5L", "/w/a.jpg"),
                monitor("eDP-1", "BOE 0x0BCA", "/w/b.png"),
            ],
            Blur { passes: 2, size: 5 },
        );
        assert_eq!(out.config.matches("background {").count(), 2);
        assert!(out.config.contains("monitor = desc:Dell Inc. U2518D TBQ5L"));
        assert!(out.config.contains("monitor = desc:BOE 0x0BCA"));
        assert!(out.config.contains("path = /w/a.jpg"));
        assert!(out.config.contains("blur_passes = 2"));
        assert!(out.config.contains("blur_size = 5"));
        assert!(out.rejected.is_empty(), "{:?}", out.rejected);
    }

    #[test]
    fn generated_blocks_outrank_the_default_background() {
        // hyprlock defaults a background to zindex -1; ours must be above it
        // so the draw order does not depend on sort stability.
        let out = render_config("", &[monitor("DP-1", "", "/w/a.jpg")], Blur::default());
        // The ordering itself is asserted at compile time next to the
        // constants; here we only check it reaches the generated config.
        assert!(out.config.contains(&format!("zindex = {GENERATED_ZINDEX}")));
    }

    #[test]
    fn falls_back_to_the_port_name_without_a_description() {
        let out = render_config("", &[monitor("DP-1", "   ", "/w/a.jpg")], Blur::default());
        assert!(out.config.contains("monitor = DP-1"));
        assert!(!out.config.contains("desc:"));
    }

    #[test]
    fn unsafe_description_falls_back_to_the_port_name() {
        let out = render_config(
            "",
            &[monitor("DP-1", "weird # display", "/w/a.jpg")],
            Blur::default(),
        );
        assert!(out.config.contains("monitor = DP-1"));
    }

    #[test]
    fn rejects_paths_hyprlang_cannot_express() {
        let out = render_config(
            "",
            &[
                monitor("DP-1", "", "/w/inject\nexit_on_fail = true"),
                monitor("DP-2", "", "/w/has#hash.jpg"),
                monitor("DP-3", "", "/w/fine.jpg"),
            ],
            Blur::default(),
        );
        assert_eq!(out.rejected.len(), 2);
        assert!(!out.config.contains("exit_on_fail"));
        assert!(!out.config.contains("has#hash"));
        assert!(out.config.contains("/w/fine.jpg"));
        assert_eq!(out.config.matches("background {").count(), 1);
    }

    #[test]
    fn blocks_are_ordered_by_port_name() {
        let out = render_config(
            "",
            &[
                monitor("DP-9", "", "/w/z.jpg"),
                monitor("DP-1", "", "/w/a.jpg"),
            ],
            Blur::default(),
        );
        let first = out.config.find("/w/a.jpg");
        let second = out.config.find("/w/z.jpg");
        assert!(first < second, "output must be deterministic");
    }

    #[test]
    fn detects_a_monitorless_background() {
        assert!(has_monitorless_background(
            "background {\n    path = /w/a.jpg\n    blur_passes = 1\n}\n"
        ));
        assert!(has_monitorless_background(
            "background {\n    monitor =\n    path = /w/a.jpg\n}\n"
        ));
    }

    #[test]
    fn detects_an_all_monitor_specific_config() {
        assert!(!has_monitorless_background(
            "background {\n    monitor = DP-1\n    path = /w/a.jpg\n}\n"
        ));
        assert!(!has_monitorless_background(
            "general {\n    hide_cursor = true\n}\n"
        ));
        assert!(!has_monitorless_background(""));
    }

    #[test]
    fn monitorless_detection_ignores_comments_and_other_blocks() {
        let base = "# background {\n\
                    input-field {\n    monitor =\n    size = 250, 60\n}\n\
                    background {\n    monitor = DP-1\n    path = /w/a.jpg\n}\n";
        assert!(
            !has_monitorless_background(base),
            "a monitor-less input-field is not a monitor-less background"
        );
    }
}
